export const Products = [
  {
    id: 1,
    title: "JBL 5510 BT Headphones",
    price: 149.99,
    imageSrc: "/images/jbl-5510-bt.jpg",
  },
  {
    id: 2,
    title: "Samsung Galaxy S21",
    price: 899.99,
    imageSrc: "/images/samsung-galaxy-s21.jpg",
  },
  {
    id: 3,
    title: "Sony 65-inch 4K Smart TV",
    price: 1299.99,
    imageSrc: "/images/sony-4k-tv.jpg",
  },
  {
    id: 4,
    title: "Apple MacBook Air",
    price: 1099.99,
    imageSrc: "/images/macbook-air.jpg",
  },
  {
    id: 5,
    title: "Canon EOS R5 Camera",
    price: 3499.99,
    imageSrc: "/images/canon-eos-r5.jpg",
  },
  {
    id: 6,
    title: "Dyson V11 Cordless Vacuum",
    price: 599.99,
    imageSrc: "/images/dyson-v11.jpg",
  },
  {
    id: 7,
    title: "Bose QuietComfort 35 II Headphones",
    price: 299.99,
    imageSrc: "/images/bose-qc35.jpg",
  },
  {
    id: 8,
    title: "LG OLED CX 55-inch TV",
    price: 1599.99,
    imageSrc: "/images/lg-oled-cx.jpg",
  },
  {
    id: 9,
    title: "GoPro Hero 9 Black",
    price: 449.99,
    imageSrc: "/images/gopro-hero-9.jpg",
  },
  {
    id: 10,
    title: "Nintendo Switch",
    price: 299.99,
    imageSrc: "/images/nintendo-switch.jpg",
  },
  {
    id: 11,
    title: "Beats Studio3 Wireless Headphones",
    price: 249.99,
    imageSrc: "/images/beats-studio3.jpg",
  },
  {
    id: 12,
    title: "Samsung 75-inch QLED TV",
    price: 2499.99,
    imageSrc: "/images/samsung-qled-tv.jpg",
  },
  {
    id: 13,
    title: "Microsoft Surface Laptop 4",
    price: 1299.99,
    imageSrc: "/images/surface-laptop-4.jpg",
  },
  {
    id: 14,
    title: "Nikon D850 DSLR Camera",
    price: 2999.99,
    imageSrc: "/images/nikon-d850.jpg",
  },
  {
    id: 15,
    title: "iRobot Roomba 980 Vacuum",
    price: 699.99,
    imageSrc: "/images/roomba-980.jpg",
  },
  {
    id: 16,
    title: "Sennheiser HD 660 S Headphones",
    price: 499.99,
    imageSrc: "/images/sennheiser-hd660s.jpg",
  },
  {
    id: 17,
    title: "Sony 85-inch 8K Smart TV",
    price: 3999.99,
    imageSrc: "/images/sony-8k-tv.jpg",
  },
  {
    id: 18,
    title: "Apple iPad Pro",
    price: 799.99,
    imageSrc: "/images/ipad-pro.jpg",
  },
  {
    id: 19,
    title: "Canon EOS M50 Mark II Camera",
    price: 699.99,
    imageSrc: "/images/canon-eos-m50.jpg",
  },
  {
    id: 20,
    title: "Dyson Supersonic Hair Dryer",
    price: 399.99,
    imageSrc: "/images/dyson-hair-dryer.jpg",
  },
  {
    id: 21,
    title: "Bose SoundLink Revolve+ Speaker",
    price: 199.99,
    imageSrc: "/images/bose-revolve.jpg",
  },
  {
    id: 22,
    title: "Samsung Galaxy Tab S7",
    price: 549.99,
    imageSrc: "/images/galaxy-tab-s7.jpg",
  },
  {
    id: 23,
    title: "Fitbit Charge 4",
    price: 149.99,
    imageSrc: "/images/fitbit-charge-4.jpg",
  },
  {
    id: 24,
    title: "Sony WH-1000XM4 Headphones",
    price: 349.99,
    imageSrc: "/images/sony-wh1000xm4.jpg",
  },
  {
    id: 25,
    title: "LG 27-inch 4K Monitor",
    price: 399.99,
    imageSrc: "/images/lg-4k-monitor.jpg",
  },
];
